export const CLUSTER_CLIENT = Symbol('CLUSTER_CLIENT')
export const REGISTERD_FUNCTIONS = Symbol('REGISTERD_FUNCTIONS')
export const MESSAGE_TYPES = {
  COMPETITION: 'CLUSTER_CLIENT_LEADER_COMPETITION',
  SOCKET_REQUEST: 'CLUSTER_CLIENT_SOCKET_REQUEST',
  SOCKET_RESPONSE: 'CLUSTER_CLIENT_SOCKET_RESPONSE',
}
